### ISSUE TITLE
Flashlight results don't appear in spotlight since update to public beta 10.10.4

### ISSUE THREAD

**Issue by nicohein** [nate-parrott/Flashlight#494] opened 2015-05-27 11:48 UTC
After I updated Mac OS to the fourth public beta 10.10.4  (14E26a) there aren't any Flashlight results in Spotlight anymore.

FlashlightSIMBLAgent.app is still running.

After disabling and enabling flashlight these messages show up in Console:

```
com.nateparrott.Flashlight.FlashlightSIMBLAgent[3288]: SETTINGS CHANGED
com.nateparrott.Flashlight.FlashlightSIMBLAgent[3288]: warning: failed to get scripting definition from /System/Library/CoreServices/Spotlight.app; it may not be scriptable.
com.nateparrott.Flashlight.FlashlightSIMBLAgent[3288]: AppleEvents: Send port for process has no send right, port=( port:26615/0x67f7 rcv:1,send:0,d:0 limit:5) (findOrCreate()/AEMachUtils.cp #526) com.apple.main-thread
com.nateparrott.Flashlight.FlashlightSIMBLAgent[3288]: AppleEvents: Send port for process has no send right, port=( port:26615/0x67f7 rcv:1,send:0,d:0 limit:5) (findOrCreate()/AEMachUtils.cp #526) com.apple.main-thread
com.nateparrott.Flashlight.FlashlightSIMBLAgent[3288]: warning: failed to get scripting definition from /System/Library/CoreServices/Spotlight.app; it may not be scriptable.
com.nateparrott.Flashlight.FlashlightSIMBLAgent[3288]: AppleEvents: Send port for process has no send right, port=( port:26615/0x67f7 rcv:1,send:0,d:0 limit:5) (findOrCreate()/AEMachUtils.cp #526) com.apple.main-thread
com.nateparrott.Flashlight.FlashlightSIMBLAgent[3288]: AppleEvents: Send port for process has no send right, port=( port:26615/0x67f7 rcv:1,send:0,d:0 limit:5) (findOrCreate()/AEMachUtils.cp #526) com.apple.main-thread
```

Is there somebody else dealing with this issue?

**Comment by Sajonara** [comment] 2015-05-27 14:31
It is not only the public beta, but the regular developer build, too. I can confirm this issue.

**Comment by toph-allen** [comment] 2015-05-27 15:29
Same here, on both my machines running 10.10.4.

**Comment by marcocarrara** [comment] 2015-05-27 17:07
It's the same for me too, I updated my OS to 10.10.4 public beta this morning and Flashlight doesn't work anymore..

**Comment by shatteringlass** [comment] 2015-05-28 07:34
Issue is upstream  
norio-nomura/EasySIMBL#25

**Comment by yashendra2797** [comment] 2015-05-29 22:38
Same for me!

**Comment by yzlnew** [comment] 2015-05-30 06:52
Same issue for me.

**Comment by magneto** [comment] 2015-06-01 08:22
Not working for me as well.

**Comment by vicliu1990** [comment] 2015-06-01 18:42
me too


![image](https://cloud.githubusercontent.com/assets/8925514/7920334/00a369fa-08d1-11e5-8105-84fa0a0872ad.png)

**Comment by iiiGerardoiii** [comment] 2015-06-01 18:43
Same problem here, I'm on version 10.10.4 (14E26a)

**Comment by shatteringlass** [comment] 2015-06-02 09:25
Please stop reporting the issue, it's obvious we're all going to encounter this problem until there is a fix. @darwin and @norio-nomura are working upstream to get easySIMBL working.

**Comment by vicliu1990** [comment] 2015-06-09 02:57
OSX 10.11更新了，spotlight功能增强 = =

**Comment by dacz** [comment] 2015-06-13 11:02
Flashlight is not registered as an Spotlight plugin/extension. I do not know if it should be (but is not working on 10.10.4).

**Comment by FutureProg** [comment] 2015-06-29 14:01
Upon getting the app it didn't function as intended. Using OSX 10.10.3

**Comment by matthewdias** [comment] 2015-07-01 14:40
@norio-nomura has pretty much declared EasySIMBL dead. Apparently the original SIMBL works on 10.10.4. Could we switch to that?

**Comment by alanma** [comment] 2015-07-02 05:29
+1

**Comment by fuzzy76** [comment] 2015-07-03 11:30
Not quite. An altered SIMBL installation (moved to a different location owned by root) works. And since SIMBL seems abandoned, I wouldn't count on it getting updated anytime soon. It seems like Apple would like to kill the kind of injection that EasySIMBL and SIMBL relies on. :-/

**Comment by dacz** [comment] 2015-07-03 11:44
@fuzzy76 Are any instructions available how to get altered SIMBL installation... to get working flashlight?

**Comment by stididup** [comment] 2015-07-03 13:56
@fuzzy76 @dacz I up your comment. Using Flashlight is so good. This issue is boring me. Any solution?

**Comment by alicoding** [comment] 2015-07-03 17:51
I shouldn't have update to OS X 10.10.4 now I kinda regret updating that :/

**Comment by owenmead** [comment] 2015-07-04 00:12
+1 on a fresh install

**Comment by mavci** [comment] 2015-07-04 12:59
+1

**Comment by sofianhw** [comment] 2015-07-04 18:01
[issue in EasySIMBL ](https://github.com/norio-nomura/EasySIMBL/issues/25)
[How to transition from EasySIMBL to SIMBL](https://gist.github.com/hetima/51b71091aedf622f61f7) by hetima

**Comment by Ankirama** [comment] 2015-07-05 12:31
@sofianhw Sorry but I don't understand how to change this.
I installed SIMBL but I don't know what I have to move from FlashLight can you help us a little bit? :)

**Comment by mesqueeb** [comment] 2015-07-07 04:09
When will flashlight release an update?

**Comment by sergiovilar** [comment] 2015-07-08 00:09
+1

**Comment by gustavobittencourt** [comment] 2015-07-08 06:40
+1

**Comment by tth135** [comment] 2015-07-08 10:42
+1

**Comment by waxfingers** [comment] 2015-07-08 13:46
+1

**Comment by svendvd** [comment] 2015-07-08 19:24
+1

**Comment by theunraveler** [comment] 2015-07-08 19:28
Please stop +1ing this. The developer is aware of the problem.

**Comment by alicoding** [comment] 2015-07-08 19:35
Can the dev or collaborator of this repo just lock this issue until further notice? +1 isn't helpful here at all.

**Comment by owenmead** [comment] 2015-07-08 20:49
Agreed @alicoding 

If you merely want to know when progress has been made, turn on Notifications for this issues (Just to the right of the first top comment)

**Comment by dnalot** [comment] 2015-07-08 20:49
Nate hasn't been [active since May](https://github.com/nate-parrott?tab=contributions&from=2015-05-25#contributions-calendar) but I [tweeted](https://twitter.com/AppShipIt/status/618539459932389376) him in reference to this issue. Everyone just checking in—refer back to @shatteringlass's comments for explanation.

**Comment by xremix** [comment] 2015-07-09 07:50
As far as I know Nate has paused the work on the project for an internship this summer. Seems we need to wait a little.

**Comment by starkshaw** [comment] 2015-07-10 03:02
Same issue here!

**Comment by tomarrell** [comment] 2015-07-10 06:59
Can someone confirm the dev is working on the issue or do we need to come up with a fix ourselves?

**Comment by mesqueeb** [comment] 2015-07-10 07:56
I cannot believe how a project like this could be put on hold.
It's probably one of the biggest projects with most app users as flashlight probably has received half of the users from the widely used Alfred.
The author of this app could become rich as I think me and everyone who uses flashlight would easily pay a buck for this app........

**Comment by alongat** [comment] 2015-07-10 09:13
Dude, 
1. Nate don't owe anyone nothing. he can do whatever he likes.
2. this is open source, you are welcome branch out and fix it

agree with @owenmead  and @alicoding , stop spamming this thread, when dev have insights they will share, meanwhile we're spamming each-other mailboxes :)

**Comment by tomarrell** [comment] 2015-07-10 09:28
@alongat essentially you are correct. No-one owes the community anything and anyone with the ability can freely make the required fixes. 

However, this is a piece of software some people rely on for their everyday workflow. It is by no means a small project and the people with the specific skills to work on it and who have in the past should at least give an indication as to their intents for the project. By no means is anyone forcing anyone to do anything, simply word as to whether something we enjoy using regularly will be making a debut on OSX El Capitan is more than enough.

Heck I know if half the people here were able to contribute the time and skills (myself included) they would, but unfortunately not my area of expertise. Everyone relies on someone else for the maintenance of software in some form or another, no need to bash anyone for it.

**Comment by alongat** [comment] 2015-07-10 09:33
@tomarrell :) just didn't like @mesqueeb tone... 
I'm sure dev are aware how much this tool means to everyone, specially since this bug breaks it altogether.
-
I think we spammed enough, lets hope the next post in this thread will be
"we found the issue/issue fix/you need to something something as w/a"
:)

**Comment by alongat** [comment] 2015-07-10 09:34
@tomarrell :) just didn't like @mesqueeb tone...

I'm sure dev are aware how much this tool means to everyone, specially since this bug breaks it altogether.
.
I think we spammed enough, lets hope the next post in this thread will be
"we found the issue/issue fix/you need to something something as w/a"
:)

**Comment by guest4849384** [comment] 2015-07-11 16:03
Hey did anyone try this?
https://gist.github.com/hetima/51b71091aedf622f61f7

**Comment by dacz** [comment] 2015-07-11 16:27
@guest4849384 I have Flashlight installed (but not working) but I have not EasySIMBL. Should I have it?

**Comment by owenmead** [comment] 2015-07-11 18:22
Be interesting if it would work. I kind of doubt it as I would suspect the
APIs to be different. Worth a try. Anyone on this thread get it working by
substituting SIMBL?

**Comment by NilsEckelt** [comment] 2015-07-13 08:58
No. Installing SIMBL 0.9.9 didn't fixed Flashlite for me! 
We have to wait for a fix. ...Or spent some time in fixing it ourself. Happy to hear from anyone to pick up this issue.

**Comment by gemueselasagne** [comment] 2015-07-13 09:13
Hey everyone! Nate won't be fixing this as he is working at Apple for the summer. He MIGHT work on flashlight at a later point in time. Read it yourself: https://twitter.com/nateparrott/status/620336639529713664

**Comment by xremix** [comment] 2015-07-13 11:06
Isn't that what I just said above? 
I'm congratulating Nate on his internship and am happy that he stared this project. So far it doesn't make sense to discuss here further more about Nate, but only if some try finding the bug and have new statuses on that. 
Hopefully somebody has some knowledge on that part of the project, as I don't. But if I would, I'd love to help this project resuming.

**Comment by gemueselasagne** [comment] 2015-07-13 14:13
@xremix well kind of. This is the official confirmation of what you assumed. Pretty sure some are happy to read Nates tweet. Don't get the point of your comment to be honest.
I'm very thankful for what Nate did with flashlight in the past. Very excited to see if the project comes back to life somewhen.

**Comment by xremix** [comment] 2015-07-13 14:25
@gemueselasagne  Ok sorry for not being clear enough. The second part of my message was more on that discussion about him going on in this issue, not directly to your post.

**Comment by killswitch** [comment] 2015-07-13 16:45
@nate-parrott Thanks for Flashlight, it was great, I hope while at Apple you incorporate it into OS X. :) Good luck.

**Comment by auraz** [comment] 2015-07-17 10:17
Thanks, hope to see it working in the future, go back to Alfred for a while.

**Comment by xiajinchun** [comment] 2015-07-20 06:35
Me too on OS X 10.10.4

**Comment by mesqueeb** [comment] 2015-07-21 01:06
Can anyone take over this project please? I’d pay up to 5 usd for this app to work properly!!!
And a lot of people here would so too!
-- 
Luca Ban

On 2015年7月20日 at 15:36:10, Jinchun Xia (notifications@github.com) wrote:

Me too on OS X 10.10.4

**Comment by wladston** [comment] 2015-07-21 17:49
would also pay USD 5 to see this working, I never got the chance to use it, tried to install it now and saw that it isn't working :(

I call also help debug/fix, but I'm by no means an OS X expert...

**Comment by gemueselasagne** [comment] 2015-07-21 18:23
I'd pay a fiver as well.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Von: Wladston Viana Ferreira FilhoGesendet: Dienstag, 21. Juli 2015 19:49An: nate-parrott/FlashlightAntwort an: nate-parrott/FlashlightCc: gemueselasagneBetreff: Re: [Flashlight] Flashlight results don't appear in spotlight since update to public beta 10.10.4 (#494)would also pay USD 5 to see this working, I never got the chance to use it, tried to install it now and saw that it isn't working :(

I call also help debug/fix, but I'm by no means an OS X expert...

—Reply to this email directly or view it on GitHub.

**Comment by MrLoh** [comment] 2015-07-21 18:44
Cavan you PLEASE stop spamming this thread. I do won't to get notified, if something actually happens but all these completely useless messages here will not help and just spam up my mail. STOP IT, this is GitHub, it's for discussing technical issues and bugs, not for +1ing !!!

**Comment by nate-parrott** [comment] 2015-07-21 18:46
Hey all —
appreciate the concern. Just to reiterate (or not, not sure if I mentioned this) but I'm not *allowed* to be working on this while I'm at Apple. If someone else wants to get this working (and it should be possible; TotalFinder still gets code injection done on El Capitan) I'll find someone to merge the fix and issue an update.
Thanks!

**Comment by plttn** [comment] 2015-07-21 18:48
@nate-parrott Unfortunately, it looks like TotalFinder is completely broken as well as of the most recent El Capitan update.

**Comment by jimcky** [comment] 2015-07-22 02:38
Getting similar result, what's weird is that it used to work some time ago, then suddenly I find that it is not working anymore and have no ideas what have I done that made it so.

I've also tried the SIMBL solution here: https://gist.github.com/hetima/51b71091aedf622f61f7 but still no luck. The problem is that I haven't installed EasySIMBL on my Mac in the first place (might be installed by FlashLight as a dependency?). I followed the remaining steps anyway, but FlashLight is still not working.

Anyone out there has got Flashlight to work again?

Here is the logs:

21/7/15 18:25:33.804 com.nateparrott.Flashlight.FlashlightSIMBLAgent[4153]: SETTINGS CHANGED
21/7/15 18:25:33.887 com.nateparrott.Flashlight.FlashlightSIMBLAgent[4153]: warning: failed to get scripting definition from /System/Library/CoreServices/Spotlight.app; it may not be scriptable.
21/7/15 18:25:33.894 com.nateparrott.Flashlight.FlashlightSIMBLAgent[4153]: AppleEvents: Send port for process has no send right, port=( port:30063/0x756f rcv:1,send:0,d:0 limit:5) (findOrCreate()/AEMachUtils.cp #526) com.apple.main-thread
21/7/15 18:25:33.895 com.nateparrott.Flashlight.FlashlightSIMBLAgent[4153]: AppleEvents: Send port for process has no send right, port=( port:30063/0x756f rcv:1,send:0,d:0 limit:5) (findOrCreate()/AEMachUtils.cp #526) com.apple.main-thread
21/7/15 18:25:34.021 com.nateparrott.Flashlight.FlashlightSIMBLAgent[4153]: warning: failed to get scripting definition from /System/Library/CoreServices/Spotlight.app; it may not be scriptable.
21/7/15 18:25:34.021 com.nateparrott.Flashlight.FlashlightSIMBLAgent[4153]: AppleEvents: Send port for process has no send right, port=( port:30063/0x756f rcv:1,send:0,d:0 limit:5) (findOrCreate()/AEMachUtils.cp #526) com.apple.main-thread
21/7/15 18:25:34.022 com.nateparrott.Flashlight.FlashlightSIMBLAgent[4153]: AppleEvents: Send port for process has no send right, port=( port:30063/0x756f rcv:1,send:0,d:0 limit:5) (findOrCreate()/AEMachUtils.cp #526) com.apple.main-thread

**Comment by plttn** [comment] 2015-07-22 04:04
@jimcky 10.10.4 broke SIMBL.

You'd have to recompile Flashlight to use the new SIMBL, but that would only be a solution until 10.11 comes out, as code injection just flat out doesn't work anymore in El Capitan.

**Comment by dacz** [comment] 2015-07-22 08:37
@plttn Please, step-by-step instructions how to recompile Flashlight with SMIBL would be great. I'm not OSX developer, sorry. If the recompiled app may be published without need to download xcode would be even better. Thanks a lot.

**Comment by dacz** [comment] 2015-07-22 08:59
I would love the Flashlight functionality and openess (but have never chance to see it working) and I'm looking for another ways how to make it working. But I'm not OSX developer.

My general question is: do the plugins for interaction with OS and app (like creating events in Cal, sending messages with Messgs) need Spotlight functionality or Spotlight is here just for obvious way how to get user input and present output?

I'm thinking about some chat-like UI (written in js/node) that would employ all great plugins, here.

Thanks for help and opinions if you would have any.

**Comment by plttn** [comment] 2015-07-22 14:20
@dacz I don't have step by step instructions, as OSX eev isn't my area. 

What I do know from looking around: 
The code injection flashlight uses was broken in 10.10.4.
There is a way to fix it on 10.10.4
That fix is somewhat pointless, as code injection will simply not work at all on 10.11

**Comment by guest4849384** [comment] 2015-07-26 18:52
@plttn What is the way to fix the injection in 10.10.4 ?
Because nearly everyone has here 10.10.4 including me!
I will avoid updating to 10.11, as I often did if something won't going to work.

**Comment by plttn** [comment] 2015-07-26 18:56
@guest4849384 to rephrase: there is a method of code injection on 10.10.4, as totalfinder still works. What that method is though, I don't know.

**Comment by hufufuf** [comment] 2015-07-28 11:43
You can try to run the following Script : 
tell application "Spotlight" to inject SIMBL into Snow Leopard

Run it at login and it should work.
I found this workaround here : https://github.com/norio-nomura/EasySIMBL/issues/25

**Comment by mvaneijgen** [comment] 2015-07-28 12:46
@hufufuf do you need the change `Snow leopard` to `Yosemite`? `tell application "Spotlight" to inject SIMBL into Yosemite`, cause `tell application "Spotlight" to inject SIMBL into Snow Leopard` doesn't work for me on 10.10.4

**Comment by hufufuf** [comment] 2015-07-28 13:14
No, it's Snow Leopard.
But I think you have to install SIMBL too 
http://culater.net/software/SIMBL/SIMBL.php

**Comment by selaromi** [comment] 2015-07-28 13:20
Do you remember what you did specifically to make it work?
- Install SIMBL
- then Flashlight
- then ran the script?

Can you tell us this to try to replay the steps?

Thanks

On Tue, Jul 28, 2015 at 3:14 PM, hufufuf <notifications@github.com> wrote:

> No, it's Snow Leopard.
> But I think you have to install SIMBL too
> http://culater.net/software/SIMBL/SIMBL.php
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nate-parrott/Flashlight/issues/494#issuecomment-125603107>
> .
>



-- 
Ignacio Morales
Tlf +34-665332477
We Wanted To Be Astronauts

**Comment by hufufuf** [comment] 2015-07-28 13:26
Here are the steps I made.
It's really ugly and now Flashlight doesn't allow me to download new plugins from the app. But all is working.
I'm not sure all is really required but I don't want to test each step independently. You can do it if you want.

- Install SIMBL http://culater.net/software/SIMBL/SIMBL.php
- Copy SpotlightSIMBL.bundle to /Library/Application Support/SIMBL/Plugins/
- Copy Flashlight.osax to ~/Library/ScriptingAdditions/
- Disable Flashlight
- Enable Flashlight
- Run the script

SpotlightSIMBL.bundle and Flashlight.osax are in
/Applications/Flashlight.app/Contents/Library/LoginItems/FlashlightSIMBLAgent.app/Contents/PlugIns/ 
and
/Applications/Flashlight.app/Contents/Library/LoginItems/FlashlightSIMBLAgent.app/Contents/Resources/SIMBLPlugins/

**Comment by pastak** [comment] 2015-07-28 13:31
@hufufuf It works on my OSX 10.10.4 by fixing your comment :+1:

**Comment by sidmonta** [comment] 2015-07-28 13:42
@hufufuf It works, thanks 👍

**Comment by hufufuf** [comment] 2015-07-28 13:47
Please note that when the application will be updated, you will have to remove these files

**Comment by mvaneijgen** [comment] 2015-07-28 14:05
Amazing it works thanks @hufufuf

**Comment by nunoh** [comment] 2015-07-28 14:05
worked for me too :+1:  thanks @hufufuf

**Comment by wladston** [comment] 2015-07-28 14:22
@hufufuf, does this work on OS X Yosemite 10.10.4? Did you have to do anything *else* besides that 6 steps? Can anyone else confirm that these instructions work for Yosemite?

**Comment by selaromi** [comment] 2015-07-28 14:42
@hufufuf I think you're the most liked guy here. Thank you for responding
with such detailed steps.

On Tue, Jul 28, 2015 at 4:22 PM, Wladston Viana Ferreira Filho <
notifications@github.com> wrote:

> @hufufuf <https://github.com/hufufuf>, does this work on OS X Yosemite
> 10.10.4? Did you have to do anything *else* besides that 6 steps? Can
> anyone else confirm that these instructions work for Yosemite?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nate-parrott/Flashlight/issues/494#issuecomment-125625732>
> .
>



-- 
Ignacio Morales
Tlf +34-665332477
We Wanted To Be Astronauts

**Comment by mvaneijgen** [comment] 2015-07-28 14:43
@wladston it works in Yosemite. What I did is remove every instance of EasySIMBL (follow their instructions) and completely remove Flashlight using [AppCleaner](http://www.freemacsoft.net/appcleaner/) and then follow the steps of @hufufuf

**Comment by hufufuf** [comment] 2015-07-28 14:45
It is only for 10.10.4
There is no need for 10.10.3 and before. 
And I don't think this is enough for El Capitan (well, I have no idea at all if it works with El Capitan)

I didn't have to do anything else.

**Comment by hufufuf** [comment] 2015-07-28 14:51
Well, it's nothing. Just a dirty hack.
Moving the files to a place where the old SIMBL can find them. And force the injection. 
It will make the wait for the next update of the app more confortable ;)

**Comment by wladston** [comment] 2015-07-28 14:54
Great, thanks for the help :) hopefully when el capitain rolls we'll have a fix for that too.

**Comment by wladston** [comment] 2015-07-28 15:16
@hufufuf, @mvaneijgen Ok, so I did all the steps, but it didn't work. Even rebooted the machine. I moved the files doing this:

    cp -r /Applications/Flashlight.app/Contents/Library/LoginItems/FlashlightSIMBLAgent.app/Contents/Resources/SIMBLPlugins/SpotlightSIMBL.bundle "/Library/Application Support/SIMBL/Plugins"
    cp -r /Applications/Flashlight.app/Contents/Library/LoginItems/FlashlightSIMBLAgent.app/Contents/PlugIns/Flashlight.osax ~/Library/ScriptingAdditions/

What should I do for the "Run the script" part? Is just launching Spotlight enough?

**Comment by plttn** [comment] 2015-07-28 15:52
@wladston In terms of El Capitan, that'll be significantly trickier (if at all possible).

**Comment by hufufuf** [comment] 2015-07-28 16:26
@wladston open script editor and create a new script with the following line : (and yes, you have to write Snow Leopard and not Yosemite)

tell application "Spotlight" to inject SIMBL into Snow Leopard

Then launch spotlight and see if it works. It should. 
If yes, you will want to export the script as an app as you will have to run it each time you open your session. 

If it doesn't, well, bad luck I suppose. I won't be able to do much for you

**Comment by wladston** [comment] 2015-07-28 16:31
Awesome, it worked!! Thanks :) 🙇

**Comment by nate-parrott** [comment] 2015-07-29 09:08
@selaromi published a gist with [instructions on how to get Flashlight working on 10.10.4](https://gist.github.com/selaromi/59666a71387d39b5bfac).

BinaryAge, which makes a number of commercial products based on tweaking OS X system apps, has folded their hands and [said they won't be able to continue messing with system apps in El Capitan](http://blog.binaryage.com/el-capitan-update/). [1]

Outside Spotlight, I think the future of Flashlight is bright (please forgive the pun, it was practically begging to be made). [Discuss that here.](https://github.com/nate-parrott/Flashlight/issues/537).

[1] You can technically continue to tweak system apps if you reboot into a recovery partition and turn off System Integrity Protection, but user's aren't going to do that. And it's probably ridiculous to ask anyone — even a very technical user — to do it.

**Closed by nate-parrott** 2015-07-29 09:08 UTC
