### ISSUE TITLE
El Capitan Dev preview?

### ISSUE THREAD

**Issue by codeOfRobin** [nate-parrott/Flashlight#505] opened 2015-06-09 11:47 UTC
Any tips on getting Flashlight to work on El Capitan?

**Comment by nicohein** [comment] 2015-06-09 12:13
Please have a look at  issue #494

**Comment by codeofRobin** [comment] 2015-06-09 12:17
Not really. I'm not getting any errors. Just this.
Any way I can disable this safeguard?
![screen shot 2015-06-09 at 5 46 53 pm](https://cloud.githubusercontent.com/assets/5009041/8057525/a19c22b2-0ecf-11e5-9891-4ad6aef0fada.png)

**Comment by TP18** [comment] 2015-06-09 12:53
agree this is a different issue, since EasySIMBL is working again on 10.11. I have the same error message

**Comment by Sajonara** [comment] 2015-06-10 03:16
If someone could explain how I can build my one version? I have a dev account and xcode 7 but when I clone the repo it always says that "no code signing identities" were found and there is an error with the existing ones, which well is because I am not Nate and my certificates are different, I tried to change several options but this error persists. Maybe it just helps to compile the code with the new Xcode to be compatible with the new os, because Xcode proposed some changes which it made automatically when I said, yes sure, do it. I have no experience with Xcode... hence I don't know how to change this.

**Comment by cHemingway** [comment] 2015-06-10 15:33
@Sajonara 
Copying from my comment on issue #400, and expanding:

>
* Install all dependencies with $ [pod](https://cocoapods.org/) install
* Switching to "don't code sign" for all projects/targets in Flashlight.xcworkspace
* Remove the final "Run shell script" stage from Flashlight build phases that installs Crashlytics. I don't have an account for this service, and don't think I need one to test the build.

Code Signing can just be disabled if you are running it locally. Its needed for the app store and downloads though, as [Gatekeeper](http://en.wikipedia.org/wiki/Gatekeeper_%28OS_X%29) disables unsigned code from running by default. 
The comment I made about .pyc files on issue #400 should be fixed by now.

This should really be on the Wiki I guess

**Comment by codeofRobin** [comment] 2015-06-12 06:26
^How does building from source solve the problem?

**Comment by cHemingway** [comment] 2015-06-12 08:09
@codeofRobin. It won't on its own, but editing the source code logically let's you remove the safeguard. I mainly replied because Sajonara asked.

**Comment by kamilwaheed** [comment] 2015-06-13 14:20
Successfully built the source and manually did this:

```objective-c
if (![@[@"911", @"916", @"917", @"948"] containsObject:spotlightVersion]) {
```
(notice the addition of version "948".)

I know that's pretty lame. I know nothing about Mac Development so please spare me that. I've just been wanting to experiment.

With this change, I no longer see the error that the Spotlight version is not supported but it doesn't seem to work either.

**Comment by yzlnew** [comment] 2015-06-14 07:18
So can we expect a fix release before the public release of EI Captain？

**Comment by MrLoh** [comment] 2015-06-19 13:24
@yzlnew give the guys a break. They are obviously working on this and the EasySIMBL problem and will certainly release a fix asap, but no one knows what excactly the problem is, so noone can predict when it will be done.

**Comment by codeofRobin** [comment] 2015-06-19 15:22
@MrLoh, while I completely agree with your sentiment, I still think it's a relatively simple fix as

**Comment by codeofRobin** [comment] 2015-06-19 15:23
Oops. Pressed the wrong button while on mobile.

**Comment by MrLoh** [comment] 2015-06-19 15:59
@codeofRobin hopefully! it's really sad to not be able to use flashlight :( It's so awesome :D

**Comment by codeofRobin** [comment] 2015-06-21 08:40
I'm gonna try to fix it myself this week as soon as I can figure out how to fix the build errors. I followed the exact procedure @cHemingway   mentioned

**Comment by selaromi** [comment] 2015-07-11 13:32
@codeofRobin any luck yet?

**Comment by codeofRobin** [comment] 2015-07-11 13:34
Nope. Can barely get cocoapods to work with Xcode 7 :(

**Comment by guest4849384** [comment] 2015-07-11 21:53
<h1>Hey did anyone tried [this](https://gist.github.com/hetima/51b71091aedf622f61f7) ?<h1>
https://gist.github.com/hetima/51b71091aedf622f61f7

**Comment by nate-parrott** [comment] 2015-07-12 21:04
Hi all —
Sorry I haven't been active on the project recently. I've been working at
apple over the summer, so, as you might imagine, it's not so easy to
contribute to open source, especially something so closely related to what
I'm doing at work. If someone else manages to patch this thing to work on
OS X, I'll have someone issue an update. Best of luck!

**Comment by nate-parrott** [comment] 2015-07-29 09:10
@selaromi published a gist with [instructions on how to get Flashlight working on 10.10.4](https://gist.github.com/selaromi/59666a71387d39b5bfac).

BinaryAge, which makes a number of commercial products based on tweaking OS X system apps, has folded their hands and [said they won't be able to continue messing with system apps in El Capitan](http://blog.binaryage.com/el-capitan-update/). [1]

It doesn't make sense to continue trying to hack Spotlight. [But I think Flashlight has a bright future outside Spotlight, as its own app](https://github.com/nate-parrott/Flashlight/issues/537).

[1] You can technically continue to tweak system apps if you reboot into a recovery partition and turn off System Integrity Protection, but user's aren't going to do that. And it's probably ridiculous to ask anyone — even a very technical user — to do it.

**Closed by nate-parrott** 2015-07-29 09:10 UTC
